//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtrLog
    {
        public int id { get; set; }
        public string empID { get; set; }
        public Nullable<System.DateTime> scanDate { get; set; }
        public string location { get; set; }
        public Nullable<bool> logType { get; set; }
    }
}
