//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoostBrand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public Nullable<int> QuantityUnit { get; set; }
        public Nullable<int> ReservationTypeID { get; set; }
        public Nullable<int> QuantityReserved { get; set; }
        public Nullable<int> IsPaid { get; set; }
        public Nullable<int> EmployeeInCharge { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    }
}
