//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoostBrand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnedItem
    {
        public int ID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string ItemName { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> DateOfReturn { get; set; }
        public Nullable<int> QuantityReturned { get; set; }
        public string Reason { get; set; }
        public string Image { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string ReferenceNo { get; set; }
    }
}
