//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoostBrand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAllocationDetail
    {
        public int ID { get; set; }
        public int StockAllocationID { get; set; }
        public int ReceivingDetailID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> ContainerStorageID { get; set; }
        public Nullable<int> ContainerLocationID { get; set; }
    
        public virtual ContainerLocation ContainerLocation { get; set; }
        public virtual ContainerStorage ContainerStorage { get; set; }
        public virtual ReceivingDetail ReceivingDetail { get; set; }
        public virtual StockAllocation StockAllocation { get; set; }
    }
}
