//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoostBrand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransferDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockTransferDetail()
        {
            this.ReceivingDetails = new HashSet<ReceivingDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> StockTransferID { get; set; }
        public Nullable<int> RequisitionDetailID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsReturn { get; set; }
    
        public virtual ReasonForAdjustment ReasonForAdjustment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivingDetail> ReceivingDetails { get; set; }
        public virtual RequisitionDetail RequisitionDetail { get; set; }
    }
}
