//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoostBrand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int UserTypeID { get; set; }
        public string Department { get; set; }
        public Nullable<int> LocationID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Location Location { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
