//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemsEncoder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string GeneralName { get; set; }
        public string Attn { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string ContactPerson { get; set; }
        public string ShippingLine { get; set; }
        public string AcctDetails { get; set; }
        public string FaxNumber { get; set; }
        public string Remarks { get; set; }
    }
}
