//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syncker.LogsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogsService.LogsServiceSoap")]
    public interface LogsServiceSoap {
        
        // CODEGEN: Generating message contract since element name _log from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Synchronize", ReplyAction="*")]
        Syncker.LogsService.SynchronizeResponse Synchronize(Syncker.LogsService.SynchronizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Synchronize", ReplyAction="*")]
        System.Threading.Tasks.Task<Syncker.LogsService.SynchronizeResponse> SynchronizeAsync(Syncker.LogsService.SynchronizeRequest request);
        
        // CODEGEN: Generating message contract since element name ListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        Syncker.LogsService.ListResponse List(Syncker.LogsService.ListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/List", ReplyAction="*")]
        System.Threading.Tasks.Task<Syncker.LogsService.ListResponse> ListAsync(Syncker.LogsService.ListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SynchronizeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Synchronize", Namespace="http://tempuri.org/", Order=0)]
        public Syncker.LogsService.SynchronizeRequestBody Body;
        
        public SynchronizeRequest() {
        }
        
        public SynchronizeRequest(Syncker.LogsService.SynchronizeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SynchronizeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _log;
        
        public SynchronizeRequestBody() {
        }
        
        public SynchronizeRequestBody(string _log) {
            this._log = _log;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SynchronizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SynchronizeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Syncker.LogsService.SynchronizeResponseBody Body;
        
        public SynchronizeResponse() {
        }
        
        public SynchronizeResponse(Syncker.LogsService.SynchronizeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SynchronizeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SynchronizeResult;
        
        public SynchronizeResponseBody() {
        }
        
        public SynchronizeResponseBody(int SynchronizeResult) {
            this.SynchronizeResult = SynchronizeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="List", Namespace="http://tempuri.org/", Order=0)]
        public Syncker.LogsService.ListRequestBody Body;
        
        public ListRequest() {
        }
        
        public ListRequest(Syncker.LogsService.ListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListRequestBody {
        
        public ListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Syncker.LogsService.ListResponseBody Body;
        
        public ListResponse() {
        }
        
        public ListResponse(Syncker.LogsService.ListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ListResult;
        
        public ListResponseBody() {
        }
        
        public ListResponseBody(string ListResult) {
            this.ListResult = ListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LogsServiceSoapChannel : Syncker.LogsService.LogsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogsServiceSoapClient : System.ServiceModel.ClientBase<Syncker.LogsService.LogsServiceSoap>, Syncker.LogsService.LogsServiceSoap {
        
        public LogsServiceSoapClient() {
        }
        
        public LogsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Syncker.LogsService.SynchronizeResponse Syncker.LogsService.LogsServiceSoap.Synchronize(Syncker.LogsService.SynchronizeRequest request) {
            return base.Channel.Synchronize(request);
        }
        
        public int Synchronize(string _log) {
            Syncker.LogsService.SynchronizeRequest inValue = new Syncker.LogsService.SynchronizeRequest();
            inValue.Body = new Syncker.LogsService.SynchronizeRequestBody();
            inValue.Body._log = _log;
            Syncker.LogsService.SynchronizeResponse retVal = ((Syncker.LogsService.LogsServiceSoap)(this)).Synchronize(inValue);
            return retVal.Body.SynchronizeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Syncker.LogsService.SynchronizeResponse> Syncker.LogsService.LogsServiceSoap.SynchronizeAsync(Syncker.LogsService.SynchronizeRequest request) {
            return base.Channel.SynchronizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Syncker.LogsService.SynchronizeResponse> SynchronizeAsync(string _log) {
            Syncker.LogsService.SynchronizeRequest inValue = new Syncker.LogsService.SynchronizeRequest();
            inValue.Body = new Syncker.LogsService.SynchronizeRequestBody();
            inValue.Body._log = _log;
            return ((Syncker.LogsService.LogsServiceSoap)(this)).SynchronizeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Syncker.LogsService.ListResponse Syncker.LogsService.LogsServiceSoap.List(Syncker.LogsService.ListRequest request) {
            return base.Channel.List(request);
        }
        
        public string List() {
            Syncker.LogsService.ListRequest inValue = new Syncker.LogsService.ListRequest();
            inValue.Body = new Syncker.LogsService.ListRequestBody();
            Syncker.LogsService.ListResponse retVal = ((Syncker.LogsService.LogsServiceSoap)(this)).List(inValue);
            return retVal.Body.ListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Syncker.LogsService.ListResponse> Syncker.LogsService.LogsServiceSoap.ListAsync(Syncker.LogsService.ListRequest request) {
            return base.Channel.ListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Syncker.LogsService.ListResponse> ListAsync() {
            Syncker.LogsService.ListRequest inValue = new Syncker.LogsService.ListRequest();
            inValue.Body = new Syncker.LogsService.ListRequestBody();
            return ((Syncker.LogsService.LogsServiceSoap)(this)).ListAsync(inValue);
        }
    }
}
