//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoostBrand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receiving
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receiving()
        {
            this.ReceivingDetails = new HashSet<ReceivingDetail>();
            this.StockTransfers = new HashSet<StockTransfer>();
        }
    
        public int ID { get; set; }
        public int LocationID { get; set; }
        public int ReceivingTypeID { get; set; }
        public string ReceivingID { get; set; }
        public int RequisitionID { get; set; }
        public System.DateTime ReceivingDate { get; set; }
        public Nullable<int> EncodedBy { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public int ReceivedBy { get; set; }
        public string PONumber { get; set; }
        public string DRNumber { get; set; }
        public string VesselNumber { get; set; }
        public string VoyageNumber { get; set; }
        public string VanNumber { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string Remarks { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivingDetail> ReceivingDetails { get; set; }
        public virtual ReceivingType ReceivingType { get; set; }
        public virtual Requisition Requisition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTransfer> StockTransfers { get; set; }
    }
}
