//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoostBrand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requisition()
        {
            this.Receivings = new HashSet<Receiving>();
            this.RequisitionDetails = new HashSet<RequisitionDetail>();
        }
    
        public int ID { get; set; }
        public string RefNumber { get; set; }
        public int RequisitionTypeID { get; set; }
        public int RequestedBy { get; set; }
        public System.DateTime RequestedDate { get; set; }
        public int LocationID { get; set; }
        public Nullable<System.DateTime> DateRequired { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public string Customer { get; set; }
        public Nullable<int> ReservationTypeID { get; set; }
        public string ShipmentType { get; set; }
        public Nullable<int> DropShipID { get; set; }
        public string PaymentStatus { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<int> ReservedBy { get; set; }
        public Nullable<int> ValidatedBy { get; set; }
        public Nullable<int> Destination { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string Remarks { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receiving> Receivings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionDetail> RequisitionDetails { get; set; }
    }
}
