//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoostBrand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequisitionDetail()
        {
            this.StockTransferDetails = new HashSet<StockTransferDetail>();
        }
    
        public int ID { get; set; }
        public int RequisitionID { get; set; }
        public int ItemID { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> AprovalStatusID { get; set; }
        public string Remarks { get; set; }
    
        public virtual ApprovalStatu ApprovalStatu { get; set; }
        public virtual Item Item { get; set; }
        public virtual Requisition Requisition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTransferDetail> StockTransferDetails { get; set; }
    }
}
