//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoostBrand.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockTransfer()
        {
            this.StockAllocations = new HashSet<StockAllocation>();
        }
    
        public int ID { get; set; }
        public int LocationID { get; set; }
        public int ReceivingID { get; set; }
        public string TransferID { get; set; }
        public System.DateTime STDAte { get; set; }
        public string Driver { get; set; }
        public string Helper { get; set; }
        public int ReceivedBy { get; set; }
        public int RequestedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public int ReleasedBy { get; set; }
        public int CounterCheckedBy { get; set; }
        public int PostedBy { get; set; }
        public Nullable<int> ApprovedStatus { get; set; }
        public string Remarks { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Employee Employee3 { get; set; }
        public virtual Employee Employee4 { get; set; }
        public virtual Employee Employee5 { get; set; }
        public virtual Location Location { get; set; }
        public virtual Receiving Receiving { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockAllocation> StockAllocations { get; set; }
    }
}
