//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syncker.MyServiceReferences {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyServiceReferences.EmployeeServiceSoap")]
    public interface EmployeeServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetEmployeesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        Syncker.MyServiceReferences.GetEmployeesResponse GetEmployees(Syncker.MyServiceReferences.GetEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<Syncker.MyServiceReferences.GetEmployeesResponse> GetEmployeesAsync(Syncker.MyServiceReferences.GetEmployeesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployees", Namespace="http://tempuri.org/", Order=0)]
        public Syncker.MyServiceReferences.GetEmployeesRequestBody Body;
        
        public GetEmployeesRequest() {
        }
        
        public GetEmployeesRequest(Syncker.MyServiceReferences.GetEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesRequestBody {
        
        public GetEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Syncker.MyServiceReferences.GetEmployeesResponseBody Body;
        
        public GetEmployeesResponse() {
        }
        
        public GetEmployeesResponse(Syncker.MyServiceReferences.GetEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEmployeesResult;
        
        public GetEmployeesResponseBody() {
        }
        
        public GetEmployeesResponseBody(string GetEmployeesResult) {
            this.GetEmployeesResult = GetEmployeesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeServiceSoapChannel : Syncker.MyServiceReferences.EmployeeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceSoapClient : System.ServiceModel.ClientBase<Syncker.MyServiceReferences.EmployeeServiceSoap>, Syncker.MyServiceReferences.EmployeeServiceSoap {
        
        public EmployeeServiceSoapClient() {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Syncker.MyServiceReferences.GetEmployeesResponse Syncker.MyServiceReferences.EmployeeServiceSoap.GetEmployees(Syncker.MyServiceReferences.GetEmployeesRequest request) {
            return base.Channel.GetEmployees(request);
        }
        
        public string GetEmployees() {
            Syncker.MyServiceReferences.GetEmployeesRequest inValue = new Syncker.MyServiceReferences.GetEmployeesRequest();
            inValue.Body = new Syncker.MyServiceReferences.GetEmployeesRequestBody();
            Syncker.MyServiceReferences.GetEmployeesResponse retVal = ((Syncker.MyServiceReferences.EmployeeServiceSoap)(this)).GetEmployees(inValue);
            return retVal.Body.GetEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Syncker.MyServiceReferences.GetEmployeesResponse> Syncker.MyServiceReferences.EmployeeServiceSoap.GetEmployeesAsync(Syncker.MyServiceReferences.GetEmployeesRequest request) {
            return base.Channel.GetEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Syncker.MyServiceReferences.GetEmployeesResponse> GetEmployeesAsync() {
            Syncker.MyServiceReferences.GetEmployeesRequest inValue = new Syncker.MyServiceReferences.GetEmployeesRequest();
            inValue.Body = new Syncker.MyServiceReferences.GetEmployeesRequestBody();
            return ((Syncker.MyServiceReferences.EmployeeServiceSoap)(this)).GetEmployeesAsync(inValue);
        }
    }
}
