//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemsEncoder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int ID { get; set; }
        public string Year { get; set; }
        public string ItemCode { get; set; }
        public string POSBarCode { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public string InventoryUoM { get; set; }
        public Nullable<int> InventoryStatus { get; set; }
        public Nullable<int> LocationCode { get; set; }
        public Nullable<int> ReOrder { get; set; }
        public Nullable<int> InStock { get; set; }
        public Nullable<int> Ordered { get; set; }
        public Nullable<int> Committed { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<int> MinimumInventory { get; set; }
        public Nullable<int> MaximumInventory { get; set; }
        public Nullable<int> DailyAverageUsage { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public string SalesDescription { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
